# Generated by Django 4.1.3 on 2022-11-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='posts',
            field=models.ManyToManyField(blank=True, to='posts.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='hashtags',
            field=models.ManyToManyField(blank=True, to='posts.hashtag'),
        ),
    ]
